# Site Settings
title: Gruppi Sepolti
email: gruppisepolti@gmail.com
description: Gruppi sepolti dall'Emilia Romagna
baseurl: "" # the subpath of your site, e.g. /blog
url: https://gruppisepolti.it" # the base hostname & protocol for your site
google_analytics: "UA-148475434-1"

# User Settings
username: Gruppi Sepolti
user_description: Some text about you.
disqus_shortname: gruppi-sepolti

# Social Media
# Remove the item if you don't need it
# github_username: muffo
# facebook_username: facebook_username
twitter_username: gruppisepolti
# instagram_username: insta2gram_username
# linkedin_username: linkedin_username
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contatti
    url: /contact/

# Exclude my node/Gem related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor', 'script']
